apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-demo-deployment
  labels:
    app: mlops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-demo
  template:
    metadata:
      labels:
        app: mlops-demo
    spec:
      containers:
      - name: mlops-demo
        image: suresh394/mlops-demo:latest
        ports:
        - containerPort: 80
        env:
        - name: WELCOME_MESSAGE
          value: "Welcome to MLOps with Suresh Raju Vetukuri"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: mlops-demo-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: mlops-demo
